name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Clear electron-builder cache
      shell: pwsh
      run: Remove-Item -Recurse -Force "$env:LOCALAPPDATA\electron-builder\Cache" -ErrorAction SilentlyContinue

    - name: Build application
      run: npm run build

    - name: Build Electron app (Windows)
      run: npx electron-builder --win --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USE_HARD_LINKS: false

    - name: List build output
      run: |
        echo "Listing electron-dist directory:"
        if (Test-Path "electron-dist") {
          Get-ChildItem -Path "electron-dist" -Recurse | Select-Object FullName, Length
          echo "Listing all .exe files:"
          Get-ChildItem -Path "electron-dist" -Filter *.exe | Select-Object FullName, Length
        } else {
          echo "electron-dist directory does not exist"
        }

    - name: Upload artifacts
      if: ${{ hashFiles('electron-dist/*.exe') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: |
          electron-dist/*.exe
          electron-dist/*.exe.blockmap
          electron-dist/latest.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-artifacts/*
        body: |
          ## ✨ Değişiklikler
          - Uygulama güncellendi
          
          ## 📥 Kurulum
          **Windows**: `.exe` dosyasını indirin ve çalıştırın
          
          ## 🔄 Otomatik Güncelleme
          Bu sürümden itibaren uygulama otomatik olarak güncellenecektir.
          Ayarlar → Otomatik Güncelleme'den kontrol edebilirsiniz.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}