name: Build and Release

on:
  push:
    branches:
      - main   # sadece main branch push'larında çalışır

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bump version
        id: bump_version
        run: |
          $oldVersion = (Get-Content package.json | ConvertFrom-Json).version
          npm version patch --no-git-tag-version
          $newVersion = (Get-Content package.json | ConvertFrom-Json).version
          echo "old_version=$oldVersion" >> $env:GITHUB_OUTPUT
          echo "new_version=$newVersion" >> $env:GITHUB_OUTPUT

      - name: Build application
        run: npm run build

      - name: Build Windows exe
        run: npx electron-builder --win

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          name: Release v${{ steps.bump_version.outputs.new_version }}
          files: dist/*.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}